fix: Use signed char to avoid compiler error
Under arm64 architectures the use of a negative char results in an error
of

> error: enumerator value ‘-1’ is outside the range of underlying type ‘char’

At the request of the project maintainer, use a `signed char` instead of
changing the values of the enum.

c.f. https://github.com/pkomiske/Wasserstein/ Issue 3